=== Tidsrom (dct:PeriodOfTime) [[Tidsrom-egenskaper]]

Klassen _Tidsrom_ er valgfri.

==== Anbefalte egenskaper for klassen _Tidsrom_ [[Anbefalte-egenskaper-Tidsrom]]

===== Tidsrom: sluttdato/tid (dcat:endDate) [[Tidsrom-sluttdato]]

[cols="30s,70d"]
|===
|Engelsk navn|end date
|URI|dcat:endDate
|Range|rdfs:Literal typed as xsd:date or xsd:dateTime
|Beskrivelse|Definerer slutten på tidsrommet.
|Multiplisitet|0..1
|Kravsnivå|Anbefalt
|===

NOTE: Vær oppmerksom på at selv om begge egenskapene anbefales, må en av de to være til stede for hver forekomst av klassen `dct:PeriodOfTime` (hvis klassen er brukt). Starten av perioden bør forstås som starten på datoen, timen, minuttet (f.eks. starter ved midnatt på begynnelsen av dagen hvis verdien er en dato). Slutten av perioden skal forstås som slutten av datoen, timen, minuttet (f.eks. slutter ved midnatt på slutten av dagen hvis verdien er en dato).

===== Tidsrom: startdato/tid (dcat:startDate) [[Tidsrom-startdata]]

[cols="30s,70d"]
|===
|Engelsk navn|start date
|URI|dcat:startDate
|Range|rdfs:Literal typed as xsd:date or xsd:dateTime
|Beskrivelse|Definerer starten på tidsrommet.
|Multiplisitet|0..1
|Kravsnivå|Anbefalt
|===
