name: build adocs and publish v1 to staging

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: v1

      - name: Build html
        id: adocbuild
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"

      - name: Build pdf
        id: adocbuild_pdf
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf -D docs -o files/modelldcat-ap-no.pdf -a lang=nb docs/main.adoc"
        continue-on-error: true

      - name: Upload rdf to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-rdf
        with:
          ontology-type: "specification"
          ontology: "modelldcat-ap-no"
          host: "https://staging.fellesdatakatalog.digdir.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY_STAGING }}
          files: |
            docs/index.html text/html nb
            docs/files/modelldcat-ap-no.pdf application/pdf nb files/modelldcat-ap-no.pdf
            docs/files/ModellDcat_AP_NOv1_2_20220826.eapx application/octet-stream nb files/ModellDcat_AP_NOv1_2_20220826.eapx
            docs/images/digitaliseringsdirektoratet.png image/png nb images/digitaliseringsdirektoratet.png
            docs/images/ModellDcat_AP_NOv1_2_20220826.png image/png nb images/ModellDcat_AP_NOv1_2_20220826.png
            docs/images/Digdir.png image/png nb images/Digdir.png
