name: Build and publish docs v1.4 to GitHub pages

permissions:
  contents: write

on:
  push:
    branches:
      - v1.4
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  build-adocs:
    name: asciidoctor build
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/develop'
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    with:
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/modelldcat-ap-no.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      publish_branch: gh-pages
      publish_dir: ./docs
      destination_dir: ./specification
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
