name: Publish README to GitHub pages

on:
  push:
    branches:
      - develop
    paths:
      - README.md
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: copy README
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to output branch.
        env:
          TARGET_BRANCH: "gh-pages"
        run: |
          files=$(find . -maxdepth 1 -name "README.md") # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "Updating index.md"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
